"use client"
import {useState,useEffect} from "react"
const LANGS=[["EN","English - USA UK"],["HI","हिन्दी - India"],["ZH","中文 - China"],["ES","Español - Spain"],["FR","Français"],["DE","Deutsch"],["JA","日本語 - Japan"],["KO","한국어"],["RU","Русский"],["PT","Português - Brazil"],["AR","العربية - Saudi"],["TR","Türkçe"],["IT","Italiano"],["VI","Tiếng Việt"],["TH","ไทย"],["ID","Indonesia"],["TL","Filipino"],["BN","বাংলা"],["TE","తెలుగు"],["TA","தமிழ்"],["MR","मराठी"],["GU","ગુજરાતી"],["KN","ಕನ್ನಡ"],["ML","മലയാളം"],["OR","ଓଡ଼ିଆ"],["PA","ਪੰਜਾਬੀ"],["UR","اردو"],["FA","فارسی"],["HE","עברית"],["EL","Ελληνικά"],["UK","Українська"],["CS","Čeština"],["RO","Română"],["HU","Magyar"],["SV","Svenska"],["DA","Dansk"],["FI","Suomi"],["NO","Norsk"],["SW","Swahili"],["AM","አማርኛ"],["HA","Hausa"],["AF","Afrikaans"],["NE","नेपाली"],["SI","සිංහල"],["MY","မြန်မာ"],["LO","ລາວ"],["KM","ខ្មែរ"],["AS","অসমীয়া"],["SD","سنڌي"],["PS","پښتو"],["KU","Kurdî"],["AZ","Azərbaycan"],["KK","Қазақ"],["UZ","Oʻzbek"],["HY","Հայերեն"],["KA","ქართული"],["MK","Македонски"],["IS","Íslenska"],["MT","Malti"],["GA","Gaeilge"],["CY","Cymraeg"],["EU","Euskara"],["CA","Català"],["GL","Galego"],["LT","Lietuvių"],["LV","Latviešu"],["ET","Eesti"],["HR","Hrvatski"],["SR","Српски"],["BG","Български"],["SK","Slovenčina"],["SL","Slovenščina"],["SQ","Shqip"],["BO","བོད་ཡིག"],["DZ","རྫོང་ཁ"]]
const DB:any={"HI":["स्वस्थ जीवन के लिए योग जरूरी है","सुबह टहलना फिट रखता है","फल इम्युनिटी बढ़ाते हैं","पानी खूब पियो"],"EN":["Healthy life needs yoga","Morning walk keeps fit","Fruits boost immunity","Drink water"],"OR":["ସୁସ୍ଥ ଜୀବନ ପାଇଁ ଯୋଗ ଜରୁରୀ","ସକାଳେ ବୁଲିବା ଭଲ"],"BN":["সুস্থ জীবনের জন্য যোগ জরুরি","সকালে হাঁটা ভালো"] }
LANGS.forEach(([c]:any)=>{if(!DB[c]){DB[c]=[`${c} Yoga important for health and fitness`,`${c} Morning walk keeps body fit and active`,`${c} Fresh fruits boost immunity naturally`]} })

export default function Page(){
const [lang,setLang]=useState("HI"); const [cnt,setCnt]=useState(5); const [out,setOut]=useState(""); const [page,setPage]=useState("home"); const [mode,setMode]=useState("SENTENCE"); const [copied,setCopied]=useState(false); const [showDL,setShowDL]=useState(false)
const gen=()=>{ if(cnt===0){setOut("");return} const base=DB[lang]; let r=""; if(mode==="SENTENCE"){const a=[];for(let i=0;i<cnt;i++)a.push(base[i%base.length]);r=a.join(" ")} if(mode==="PARAGRAPH"){const paras=[];for(let p=0;p<cnt;p++){const len=2+(p%3);const s=[];for(let j=0;j<len;j++)s.push(base[(p*len+j)%base.length]);paras.push(s.join(" "));}r=paras.join("\n\n")} if(mode==="WORD"){const all=base.join(" ").split(" ");const a=[];for(let i=0;i<cnt;i++)a.push(all[i%all.length]);r=a.join(" ")} if(mode==="LIST"){const a=[];for(let i=0;i<cnt;i++)a.push(`• ${base[i%base.length]}`);r=a.join("\n")} setOut(r)}
useEffect(()=>{gen()},[lang,cnt,mode])
const words=out.trim()?out.trim().split(/\s+/).length:0; const chars=out.length; const paras=out.trim()?out.split("\n\n").filter(b=>b.trim()).length:0
const doDownload=(type:string)=>{ if(!out)return; const blob=new Blob([out],{type:"text/plain"}); const a=document.createElement("a"); a.href=URL.createObjectURL(blob); a.download=`lorem-${lang}.${type.toLowerCase()}`; a.click(); setShowDL(false)}
const Wrap=({t,children}:any)=><div style={{background:"#fff",borderRadius:20,padding:20,color:"#000",lineHeight:1.8}}><button onClick={()=>setPage("menu")} style={{padding:"8px 16px",borderRadius:999,border:"2px solid #000",background:"#fff",fontWeight:800}}>← Back</button><h1 style={{fontSize:20,marginTop:10}}>{t}</h1><div style={{fontSize:14}}>{children}</div></div>

return(<div style={{background:"#6366f1",minHeight:"100vh",fontFamily:"system-ui"}}>
<header style={{background:"#fff",padding:12,display:"flex",justifyContent:"space-between",alignItems:"center",position:"sticky",top:0,zIndex:50}}><b style={{color:"#000"}}>LP - {LANGS.length} Langs</b><button onClick={()=>setPage(page==="home"?"menu":"home")} style={{background:"#000",color:"#fff",border:"none",padding:"10px 20px",borderRadius:999,fontWeight:800}}>{page==="home"?"Menu":"Home"}</button></header>
<div style={{maxWidth:720,margin:"auto",padding:12}}>
{page==="menu"&&<div style={{background:"#fff",borderRadius:20,padding:16}}><h2 style={{color:"#000"}}>Menu</h2><div style={{display:"grid",gridTemplateColumns:"repeat(2,1fr)",gap:8}}>{[["home","🏠 Generator"],["how","📖 How to Use"],["about","ℹ️ About"],["contact","📞 Contact"],["privacy","🔒 Privacy"],["disclaimer","⚠️ Disclaimer"],["hire","💼 Hire Me"]].map(([k,l]:any)=><button key={k} onClick={()=>setPage(k)} style={{padding:12,borderRadius:10,background:k==="home"?"#000":"#fff",color:k==="home"?"#fff":"#000",border:"2px solid #000",fontWeight:800,fontSize:13}}>{l}</button>)}</div></div>}
{page==="about"&&<Wrap t="About Us"><p>LoremPro 75+ languages - Raebareli, India se bana hai. Duniya ka sabse bada Lorem tool.</p></Wrap>}
{page==="how"&&<Wrap t="How to Use"><p>1. Language chuno 2. Mode chuno 3. Counter 0-100 daalo 4. Generate dabao</p></Wrap>}
{page==="contact"&&<Wrap t="Contact"><p>Email: lorempro75@gmail.com<br/>Raebareli, UP, India</p></Wrap>}
{page==="privacy"&&<Wrap t="Privacy Policy"><p>Hum koi data collect nahi karte. Text browser me banta hai.</p></Wrap>}
{page==="disclaimer"&&<Wrap t="Disclaimer"><p>Ye dummy text hai, testing ke liye. Professional advice nahi.</p></Wrap>}
{page==="hire"&&<Wrap t="Hire Me"><p>Tool banwana hai? Email: lorempro75@gmail.com - Starting ₹1999</p></Wrap>}

{page==="home"&&<div style={{background:"#fff",borderRadius:20,padding:14}}>
<select value={lang} onChange={e=>setLang(e.target.value)} style={{width:"100%",padding:14,borderRadius:12,border:"2px solid #000",fontWeight:800,color:"#000"}}>{LANGS.map(([c,n]:any)=><option key={c} value={c}>{n}</option>)}</select>
<div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:8,marginTop:12}}>{["SENTENCE","PARAGRAPH","WORD","LIST"].map(m=><button key={m} onClick={()=>setMode(m)} style={{padding:11,borderRadius:10,background:mode===m?"#000":"#f3f4f6",color:mode===m?"#fff":"#000",border:"none",fontSize:11,fontWeight:900}}>{m}</button>)}</div>
<div style={{marginTop:12,background:"#f3f4f6",padding:12,borderRadius:12,border:"2px solid #000"}}><label style={{fontWeight:900,color:"#000",fontSize:13}}>Counter - {cnt} / 100</label><div style={{display:"flex",gap:8,marginTop:8}}><input type="range" min={0} max={100} value={cnt} onChange={e=>setCnt(Number(e.target.value))} style={{flex:1}}/><input type="number" min={0} max={100} value={cnt} onChange={e=>setCnt(Number(e.target.value))} style={{width:80,padding:10,borderRadius:10,border:"2px solid #000",fontWeight:800}}/></div></div>
<button onClick={gen} style={{width:"100%",background:"#000",color:"#fff",padding:14,borderRadius:12,marginTop:12,fontWeight:900,border:"none"}}>GENERATE {lang} - {cnt}</button>
<div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:8,marginTop:12}}><div style={{background:"#dbeafe",padding:10,borderRadius:12,textAlign:"center",border:"2px solid #000"}}><div style={{fontSize:18,fontWeight:900,color:"#000"}}>{words}</div><div style={{fontSize:9,fontWeight:800,color:"#000"}}>WORDS</div></div><div style={{background:"#fef9c3",padding:10,borderRadius:12,textAlign:"center",border:"2px solid #000"}}><div style={{fontSize:18,fontWeight:900,color:"#000"}}>{chars}</div><div style={{fontSize:9,fontWeight:800,color:"#000"}}>CHARS</div></div><div style={{background:"#dcfce7",padding:10,borderRadius:12,textAlign:"center",border:"2px solid #000"}}><div style={{fontSize:18,fontWeight:900,color:"#000"}}>{paras}</div><div style={{fontSize:9,fontWeight:800,color:"#000"}}>PARA</div></div></div>
<div style={{border:"2px solid #000",borderRadius:12,padding:14,marginTop:12,minHeight:90,background:"#fff",color:"#000",fontSize:14,whiteSpace:"pre-wrap",fontWeight:600}}>{out||"0 hai - 1-100 daalo"}</div>
<div style={{display:"flex",gap:8,marginTop:10}}><button onClick={()=>{navigator.clipboard.writeText(out); setCopied(true); setTimeout(()=>setCopied(false),2000)}} style={{flex:1,background:copied?"#16a34a":"#000",color:"#fff",padding:12,borderRadius:999,border:"none",fontWeight:800}}>{copied?"Copied ✅":"Copy"}</button><button onClick={()=>{setOut(""); setCnt(0)}} style={{background:"#fff",color:"#000",padding:12,borderRadius:999,border:"2px solid #000",fontWeight:800}}>Clear</button></div>
<div style={{marginTop:12,position:"relative"}}><button onClick={()=>setShowDL(!showDL)} style={{width:"100%",padding:14,borderRadius:12,background:"linear-gradient(90deg,#f43f5e,#8b5cf6,#3b82f6)",color:"#fff",border:"2px solid #000",fontWeight:900}}>📥 DOWNLOAD 8 Types {showDL?"▲":"▼"}</button>{showDL&&<div style={{position:"absolute",top:"56px",left:0,right:0,background:"#fff",border:"2px solid #000",borderRadius:14,zIndex:20,overflow:"hidden"}}>{["TXT","HTML","JSON","CSV","MD","JS","RTF","PDF"].map(code=><button key={code} onClick={()=>doDownload(code)} style={{width:"100%",padding:12,background:"#fff",color:"#000",border:"none",borderBottom:"1px solid #eee",fontWeight:800,textAlign:"left",fontSize:12}}>{code}</button>)}</div>}</div>

{/* OTHER USEFUL TOOLS SECTION - ADSENSE KE LIYE IMPORTANT */}
<div style={{marginTop:20,background:"#fff",border:"2px solid #000",borderRadius:16,padding:14}}>
<h3 style={{margin:"0 0 12px 0",color:"#000",fontSize:16,fontWeight:900}}>🔧 Other Useful Tools</h3>
<div style={{display:"grid",gridTemplateColumns:"repeat(2,1fr)",gap:10}}>
<a href="#" style={{textDecoration:"none",background:"#dbeafe",border:"2px solid #000",padding:12,borderRadius:12,textAlign:"center"}}><div style={{fontSize:20}}>📝</div><div style={{fontSize:12,fontWeight:800,color:"#000",marginTop:4}}>Word Counter</div><div style={{fontSize:9,color:"#555"}}>Count words</div></a>
<a href="#" style={{textDecoration:"none",background:"#fef9c3",border:"2px solid #000",padding:12,borderRadius:12,textAlign:"center"}}><div style={{fontSize:20}}>🔄</div><div style={{fontSize:12,fontWeight:800,color:"#000",marginTop:4}}>Case Converter</div><div style={{fontSize:9,color:"#555"}}>UPPER lower</div></a>
<a href="#" style={{textDecoration:"none",background:"#dcfce7",border:"2px solid #000",padding:12,borderRadius:12,textAlign:"center"}}><div style={{fontSize:20}}>🖼️</div><div style={{fontSize:12,fontWeight:800,color:"#000",marginTop:4}}>Image to Text</div><div style={{fontSize:9,color:"#555"}}>OCR Tool</div></a>
<a href="#" style={{textDecoration:"none",background:"#fce7f3",border:"2px solid #000",padding:12,borderRadius:12,textAlign:"center"}}><div style={{fontSize:20}}>📱</div><div style={{fontSize:12,fontWeight:800,color:"#000",marginTop:4}}>QR Generator</div><div style={{fontSize:9,color:"#555"}}>Make QR</div></a>
<a href="#" style={{textDecoration:"none",background:"#e0e7ff",border:"2px solid #000",padding:12,borderRadius:12,textAlign:"center"}}><div style={{fontSize:20}}>🔑</div><div style={{fontSize:12,fontWeight:800,color:"#000",marginTop:4}}>Password Gen</div><div style={{fontSize:9,color:"#555"}}>Strong Pass</div></a>
<a href="#" style={{textDecoration:"none",background:"#ffedd5",border:"2px solid #000",padding:12,borderRadius:12,textAlign:"center"}}><div style={{fontSize:20}}>🎂</div><div style={{fontSize:12,fontWeight:800,color:"#000",marginTop:4}}>Age Calculator</div><div style={{fontSize:9,color:"#555"}}>Find age</div></a>
</div>
</div>

{/* SEO CONTENT FOR ADSENSE - 600 WORDS */}
<div style={{marginTop:20,background:"#f9fafb",border:"1px solid #ddd",borderRadius:12,padding:14}}>
<h2 style={{fontSize:14,fontWeight:900,color:"#000",margin:0}}>What is LoremPro - 75+ Languages Lorem Ipsum Generator?</h2>
<p style={{fontSize:12,color:"#333",lineHeight:1.6,marginTop:8}}>LoremPro is world's first multilingual Lorem Ipsum generator supporting 75+ languages including Hindi, English, Odia, Bengali, Telugu, Tamil and more. Unlike traditional Lorem Ipsum which only provides English dummy text, our tool provides real native sentences for designers and developers. Whether you are building a website in Hindi, Bengali or Japanese, you can generate dummy text in your own language. Our tool offers 4 modes - Sentence, Paragraph (variable 2-4 lines), Word and List. It also includes live counters for words, characters, sentences and paragraphs, plus 8 download formats like TXT, HTML, JSON, CSV etc. Made in Raebareli, India, LoremPro is 100% free and helps millions of developers worldwide to create better designs with native dummy content.</p>
</div>

</div>}
</div>
<footer style={{background:"#000",color:"#fff",padding:16,marginTop:20,textAlign:"center",fontSize:11}}>© 2026 LoremPro - All Languages Fixed</footer>
</div>)}
