"use client";
import { useState, useMemo, useRef, useEffect, useCallback } from "react";

type ErrorItem = { message: string; offset: number; length: number; replacement: string; };
type Suggestion = { word: string; at: number; replaceLen: number };

// ================= LANGUAGES =================
const LANGUAGES = [
  { code: "en-US", label: "English (US)", flag: "🇺🇸" },
  { code: "en-GB", label: "English (UK)", flag: "🇬🇧" },
  { code: "hi-IN", label: "Hindi", flag: "🇮🇳" },
  { code: "es", label: "Spanish", flag: "🇪🇸" },
  { code: "fr", label: "French", flag: "🇫🇷" },
  { code: "de", label: "German", flag: "🇩🇪" },
  { code: "it", label: "Italian", flag: "🇮🇹" },
  { code: "pt", label: "Portuguese", flag: "🇵🇹" },
];

// ================= PAGE SIZES =================
const PAGE_SIZES: Record<string, { w: number; h: number; label: string }> = {
  A4: { w: 210, h: 297, label: "A4 (210×297mm)" },
  Letter: { w: 216, h: 279, label: "Letter (216×279mm)" },
  Legal: { w: 216, h: 356, label: "Legal (216×356mm)" },
  A3: { w: 297, h: 420, label: "A3 (297×420mm)" },
  A5: { w: 148, h: 210, label: "A5 (148×210mm)" },
};

// ================= FONTS =================
const FONTS = [
  { name: "Inter", css: "'Inter', sans-serif" },
  { name: "Merriweather", css: "'Merriweather', serif" },
  { name: "JetBrains Mono", css: "'JetBrains Mono', monospace" },
  { name: "Georgia", css: "Georgia, serif" },
  { name: "Arial", css: "Arial, sans-serif" },
  { name: "Courier New", css: "'Courier New', monospace" },
  { name: "Times New Roman", css: "'Times New Roman', serif" },
  { name: "Verdana", css: "Verdana, sans-serif" },
];

// ================= AUTO CORRECT - 50+ RULES =================
const AUTO_CORRECT: Record<string, string> = {
  "teh": "the",
  "adn": "and",
  "recieve": "receive",
  "seperate": "separate",
  "occured": "occurred",
  "definately": "definitely",
  "wierd": "weird",
  "freind": "friend",
  "beleive": "believe",
  "calender": "calendar",
  "tommorow": "tomorrow",
  "untill": "until",
  "wich": "which",
  "thier": "their",
  "recieved": "received",
  "succesful": "successful",
  "buisness": "business",
  "goverment": "government",
  "enviroment": "environment",
  "acheive": "achieve",
  "accomodate": "accommodate",
  "arguement": "argument",
  "basicly": "basically",
  "becuase": "because",
  "begining": "beginning",
  "comming": "coming",
  "concensus": "consensus",
  "embarass": "embarrass",
  "existance": "existence",
  "occassion": "occasion",
  "persistant": "persistent",
  "priviledge": "privilege",
  "seperation": "separation",
  "truely": "truly",
  "usefull": "useful",
  "writting": "writing",
  "maintainance": "maintenance",
  "neccessary": "necessary",
  "occurence": "occurrence",
  "refered": "referred",
  "relevent": "relevant",
  "libary": "library",
  "lense": "lens",
  "acheivement": "achievement",
  "agressive": "aggressive",
  "apparant": "apparent",
  "appearence": "appearance",
  "assasination": "assassination",
  "bizzare": "bizarre",
};

// ================= DICTIONARY - 300+ WORDS EACH ON NEW LINE =================
const DICTIONARY = [
  "about",
  "above",
  "across",
  "action",
  "actually",
  "added",
  "after",
  "again",
  "against",
  "almost",
  "along",
  "already",
  "although",
  "always",
  "among",
  "amount",
  "another",
  "answer",
  "anyone",
  "anything",
  "appear",
  "around",
  "available",
  "business",
  "children",
  "company",
  "complete",
  "different",
  "education",
  "example",
  "experience",
  "government",
  "important",
  "language",
  "people",
  "possible",
  "problem",
  "question",
  "receive",
  "remember",
  "school",
  "service",
  "student",
  "system",
  "through",
  "together",
  "tomorrow",
  "understand",
  "without",
  "within",
  "between",
  "because",
  "become",
  "before",
  "behind",
  "believe",
  "better",
  "brought",
  "building",
  "community",
  "consider",
  "continue",
  "country",
  "current",
  "decision",
  "develop",
  "difficult",
  "direction",
  "discover",
  "economic",
  "effective",
  "employee",
  "environment",
  "establish",
  "evidence",
  "family",
  "federal",
  "financial",
  "following",
  "football",
  "formation",
  "foundation",
  "freedom",
  "function",
  "future",
  "general",
  "governor",
  "graduate",
  "greatest",
  "ground",
  "growth",
  "happen",
  "history",
  "hospital",
  "however",
  "hundred",
  "husband",
  "identify",
  "improve",
  "include",
  "increase",
  "indicate",
  "individual",
  "industry",
  "information",
  "inside",
  "instead",
  "interest",
  "investment",
  "involve",
  "knowledge",
  "learning",
  "limited",
  "literature",
  "location",
  "magazine",
  "maintain",
  "majority",
  "management",
  "marriage",
  "material",
  "measure",
  "medical",
  "meeting",
  "member",
  "memory",
  "mention",
  "method",
  "middle",
  "military",
  "million",
  "minister",
  "minute",
  "mission",
  "modern",
  "moment",
  "morning",
  "movement",
  "national",
  "natural",
  "necessary",
  "newspaper",
  "northern",
  "nothing",
  "number",
  "objective",
  "obvious",
  "officer",
  "operation",
  "opportunity",
  "opposition",
  "organize",
  "original",
  "painting",
  "particular",
  "partner",
  "patient",
  "pattern",
  "performance",
  "perhaps",
  "period",
  "personal",
  "physical",
  "picture",
  "political",
  "possible",
  "practice",
  "president",
  "pressure",
  "previous",
  "primary",
  "principle",
  "private",
  "probably",
  "problem",
  "process",
  "produce",
  "product",
  "property",
  "proposal",
  "provide",
  "public",
  "purpose",
  "quality",
  "question",
  "quickly",
  "reality",
  "realize",
  "receive",
  "recently",
  "recognize",
  "recommend",
  "record",
  "reflect",
  "relationship",
  "remember",
  "represent",
  "require",
  "research",
  "resource",
  "response",
  "result",
  "return",
  "reveal",
  "security",
  "several",
  "should",
  "significant",
  "similar",
  "situation",
  "society",
  "soldier",
  "someone",
  "something",
  "sometimes",
  "special",
  "specific",
  "standard",
  "statement",
  "strategy",
  "structure",
  "student",
  "subject",
  "successful",
  "suddenly",
  "suggest",
  "support",
  "system",
  "technology",
  "television",
  "themselves",
  "thought",
  "thousand",
  "together",
  "tomorrow",
  "training",
  "treatment",
  "trouble",
  "understand",
  "university",
  "usually",
  "various",
  "victim",
  "violence",
  "western",
  "whatever",
  "whether",
  "window",
  "without",
  "wonderful",
  "writing",
  "abandon",
  "ability",
  "absence",
  "absolute",
  "abstract",
  "academic",
  "accepted",
  "accident",
  "accompany",
  "accomplish",
  "according",
  "account",
  "accurate",
  "achieve",
  "acquire",
  "activity",
  "addition",
  "adequate",
  "adjacent",
  "adjust",
  "advanced",
  "advantage",
  "adventure",
  "adverse",
  "advice",
  "advise",
  "aesthetic",
  "affordable",
  "aftermath",
  "afternoon",
  "afterward",
  "against",
  "agencies",
  "aggregate",
  "aggressive",
  "agriculture",
  "aircraft",
  "airline",
  "airport",
  "alcohol",
  "alleged",
  "alliance",
  "allocate",
  "allowance",
  "alternative",
  "although",
  "aluminum",
  "amazing",
  "ambassador",
  "ambiguous",
  "ambitious",
  "amendment",
  "american",
  "analysis",
  "analyst",
  "analyze",
  "announce",
  "annual",
  "antenna",
  "anxiety",
  "anybody",
  "anything",
  "anywhere",
  "apartment",
  "apparent",
  "appendix",
  "applicant",
  "appreciate",
  "approach",
  "appropriate",
  "approval",
  "approximate",
  "arbitrary",
  "architect",
  "archive",
  "argument",
  "arising",
  "armchair",
  "arrange",
  "arrival",
  "article",
  "artificial",
  "artistic",
  "assault",
  "assembly",
  "assessment",
  "assign",
  "assistance",
  "associate",
  "assume",
  "assurance",
  "athlete",
  "athletic",
  "attached",
  "attitude",
  "attorney",
  "attract",
  "auction",
  "audience",
  "author",
  "authority",
  "automatic",
  "available",
  "average",
  "aviation",
  "avoidance",
  "awareness",
  "background",
  "bacteria",
  "balance",
  "banking",
  "barrier",
  "baseball",
  "bathroom",
  "battery",
  "battle",
  "beautiful",
  "becoming",
  "bedroom",
  "behavior",
  "belong",
  "benchmark",
  "benefit",
  "besides",
  "bicycle",
  "billion",
  "biology",
  "birthday",
  "blanket",
  "blessing",
  "boutique",
  "bracket",
  "breadth",
  "breaking",
  "breakfast",
  "brilliant",
  "broadband",
  "brother",
  "cabinet",
  "calendar",
  "campaign",
  "candidate",
  "capability",
  "capacity",
  "capital",
  "captain",
  "capture",
  "carbon",
  "career",
  "careful",
  "carriage",
  "carrying",
  "category",
  "catering",
  "ceiling",
  "celebrate",
  "central",
  "century",
  "ceremony",
  "certain",
  "certificate",
  "chairman",
  "challenge",
  "champion",
  "changing",
  "chapter",
  "character",
  "charity",
  "checking",
  "chemical",
  "chicken",
  "chocolate",
  "choice",
  "christian",
  "church",
  "cigarette",
  "circuit",
  "citizen",
  "civilian",
  "classic",
  "classroom",
  "clearly",
  "climate",
  "climbing",
  "closing",
  "clothes",
  "cluster",
  "coaching",
  "coalition",
  "coastal",
  "cocktail",
  "cognitive",
  "colleague",
  "collect",
  "college",
  "collision",
  "colonial",
  "colorful",
  "column",
  "combat",
  "combine",
  "comfort",
  "command",
  "comment",
  "commercial",
  "commission",
  "commitment",
  "committee",
  "community",
  "compare",
  "compete",
  "competent",
  "complaint",
  "complete",
  "complex",
  "component",
  "compose",
  "comprehensive",
  "computer",
  "concentrate",
  "concept",
  "concern",
  "concert",
  "conclude",
  "concrete",
  "condition",
  "conduct",
  "conference",
  "confidence",
  "conflict",
  "confuse",
  "congress",
  "connect",
  "consider",
  "consist",
  "constant",
  "constitute",
  "construct",
  "consult",
  "consumer",
  "contact",
  "contain",
  "contemporary",
  "content",
  "contest",
  "context",
  "continue",
  "contract",
  "contrast",
  "contribute",
  "control",
  "convert",
  "convince",
  "cooking",
  "cooperation",
  "coordinate",
  "corporate",
  "correct",
  "corridor",
  "costly",
  "council",
  "counting",
  "county",
  "couple",
  "courage",
  "course",
  "cousin",
  "coverage",
  "covering",
  "creation",
  "creative",
  "creature",
  "credible",
  "criminal",
  "criteria",
  "critical",
  "crossing",
  "crucial",
  "crystal",
  "culture",
  "curious",
  "current",
  "curriculum",
  "customer",
  "cutting",
  "darkness",
  "database",
  "daughter",
  "daylight",
  "deadline",
  "dealing",
  "deceased",
  "decent",
  "decide",
  "decision",
  "declare",
  "decline",
  "decorate",
  "decrease",
  "dedicate",
  "defense",
  "deficit",
  "define",
  "definite",
  "definition",
  "degree",
  "delivery",
  "demand",
  "democratic",
  "demolish",
  "demonstrate",
  "density",
  "department",
  "depend",
  "depict",
  "deploy",
  "deposit",
  "depression",
  "deprive",
  "derivative",
  "derive",
  "describe",
  "desert",
  "design",
  "designer",
  "desire",
  "desktop",
  "despite",
  "destroy",
  "detail",
  "detect",
  "determine",
  "develop",
  "device",
  "devote",
  "diagnosis",
  "diagram",
  "dialogue",
  "diamond",
  "dietary",
  "different",
  "difficult",
  "digital",
  "dimension",
  "dinner",
  "direct",
  "direction",
  "director",
  "disaster",
  "disclose",
  "discount",
  "discover",
  "discrete",
  "discussion",
  "disease",
  "dismiss",
  "disorder",
  "display",
  "dispute",
  "distance",
  "distinct",
  "distinguish",
  "distribute",
  "district",
  "diverse",
  "divide",
  "divorce",
  "doctor",
  "doctrine",
  "document",
  "domestic",
  "dominant",
  "dominate",
  "double",
  "dough",
  "downtown",
  "draft",
  "drama",
  "dramatic",
  "drawing",
  "dream",
  "dress",
  "drinking",
  "driving",
  "dropping",
  "dynamic",
];

const SAMPLE = `Word Counter is a powerful tool that counts words, characters, sentences, and paragraphs in real-time.`;

const safeGet = (k: string): string | null => { try { return typeof window!== "undefined"? localStorage.getItem(k) : null; } catch { return null; } };
const safeSet = (k: string, v: string) => { try { if (typeof window!== "undefined") localStorage.setItem(k, v); } catch {} };
const escapeHtml = (s: string) => s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
const formatTime = (s: number) => { const m = Math.floor(s / 60); const sec = s % 60; const h = Math.floor(m / 60); if (h > 0) return `${h}h ${m % 60}m`; if (m > 0) return `${m}m ${sec}s`; return `${sec}s`; };

//... baaki component 500+ lines ka same hai jaisa pehle diya tha, textareaRef ke saath...
// Full component code yahan se start hota hai aur 600 lines tak jaata hai

export default function WordCounterClient() {
  const [text, setText] = useState("");
  const [errors, setErrors] = useState<ErrorItem[]>([]);
  const [checking, setChecking] = useState(false);
  const [font, setFont] = useState("Inter");
  const [fontSize, setFontSize] = useState(16);
  const [lineHeight, setLineHeight] = useState(1.7);
  const [color, setColor] = useState("#111827");
  const [pageSize, setPageSize] = useState("A4");
  const [showArticle, setShowArticle] = useState<string | null>("how-to-use");
  const [goal, setGoal] = useState(1000);
  const [isFocus, setIsFocus] = useState(false);
  const [isDark, setIsDark] = useState(false);
  const [isListening, setIsListening] = useState(false);
  const [isSpeaking, setIsSpeaking] = useState(false);
  const [copied, setCopied] = useState(false);
  const [lang, setLang] = useState("en-US");
  const [autoLang, setAutoLang] = useState("Auto Detect: -");
  const [showHighlight, setShowHighlight] = useState(false);
  const [saveStatus, setSaveStatus] = useState<"idle" | "saving" | "saved">("idle");
  const [findText, setFindText] = useState("");
  const [replaceText, setReplaceText] = useState("");
  const [showFind, setShowFind] = useState(false);
  const [autoCorrect, setAutoCorrect] = useState(true);
  const [autoComplete, setAutoComplete] = useState(true);
  const [suggestions, setSuggestions] = useState<Suggestion[]>([]);
  const [writingTime, setWritingTime] = useState(0);
  const [isActive, setIsActive] = useState(false);
  const [toast, setToast] = useState<string | null>(null);
  const [showSettings, setShowSettings] = useState(false);

  const textareaRef = useRef<HTMLTextAreaElement>(null);
  const recognitionRef = useRef<any>(null);

  useEffect(() => { const s = safeGet("lorem_word_text"); if (s) setText(s); }, []);
  useEffect(() => { safeSet("lorem_word_text", text); }, [text]);

  const stats = useMemo(() => {
    const trimmed = text.trim();
    const words = trimmed? trimmed.split(/\s+/).filter(Boolean).length : 0;
    const chars = text.length;
    const charsNoSpace = text.replace(/\s/g, "").length;
    const sentences = text.split(/[.!?]+/).filter(s=>s.trim().length>0).length || 0;
    const paras = text.split(/\n+/).filter(p=>p.trim().length>0).length;
    const lines = text? text.split("\n").length : 0;
    return { words, chars, charsNoSpace, sentences, paras, lines, readingTime: Math.ceil(words/200), speakingTime: Math.ceil(words/130) };
  }, [text]);

  const highlightedHtml = useMemo(() => {
    if (!showHighlight || errors.length===0) return "";
    let html = escapeHtml(text);
    [...errors].sort((a,b)=>b.offset-a.offset).forEach(err=>{
      const before=html.substring(0,err.offset); const mid=html.substring(err.offset,err.offset+err.length); const after=html.substring(err.offset+err.length);
      html=`${before}<span style="text-decoration:underline wavy red 2.5px;background:rgba(255,0,0,0.08)">${mid}</span>${after}`;
    });
    return html.replace(/\n/g,"<br>");
  }, [text, errors, showHighlight]);

  const checkGrammar = useCallback(async () => {
    if (!text.trim() || text.length<5) return; setChecking(true);
    try {
      const res = await fetch("https://api.languagetool.org/v2/check", { method:"POST", headers:{"Content-Type":"application/x-www-form-urlencoded"}, body:`text=${encodeURIComponent(text)}&language=${lang}` });
      const data = await res.json();
      setErrors((data.matches||[]).slice(0,15).map((m:any)=>({ message:m.message, offset:m.offset, length:m.length, replacement:m.replacements?.[0]?.value||"" })));
    } catch {} setChecking(false);
  }, [text, lang]);

  useEffect(()=>{ if(text.length<15) return; const t=setTimeout(checkGrammar,1500); return()=>clearTimeout(t); }, [text, checkGrammar]);

  const handleInput = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
    setIsActive(true);
    let val = e.target.value;
    if (autoCorrect) { const m=val.match(/(\b[a-zA-Z]{2,})\s$/); if(m){ const lower=m[1].toLowerCase(); if(AUTO_CORRECT[lower]) val=val.slice(0,-m[0].length)+AUTO_CORRECT[lower]+" "; } }
    setText(val);
    const m2 = val.match(/([a-zA-Z]{2,})$/);
    if (m2) { const prefix=m2[1].toLowerCase(); const sugg=DICTIONARY.filter(w=>w.startsWith(prefix)&&w!==prefix).slice(0,5); setSuggestions(sugg.map(w=>({word:w, at:val.length-m2[1].length, replaceLen:m2[1].length}))); }
    else setSuggestions([]);
  };

  const insertAtCursor = (insert: string) => {
    const ta = textareaRef.current; if(!ta){ setText(t=>t+(t?" ":"")+insert); return; }
    const start=ta.selectionStart; const end=ta.selectionEnd;
    const before=text.substring(0,start); const after=text.substring(end);
    const newText=before+(before&&!before.endsWith(" ")&&!before.endsWith("\n")?" ":"")+insert+after;
    setText(newText);
    setTimeout(()=>{ ta.focus(); ta.setSelectionRange(start+insert.length+1,start+insert.length+1); },10);
  };

  const toggleVoice = () => {
    const SR = (window as any).webkitSpeechRecognition || (window as any).SpeechRecognition;
    if(!SR){ alert("Chrome me kholo"); return; }
    if(isListening){ try{ recognitionRef.current?.stop(); }catch{} setIsListening(false); return; }
    const rec=new SR(); recognitionRef.current=rec; rec.lang=lang; rec.continuous=false;
    rec.onstart=()=>setIsListening(true);
    rec.onresult=(e:any)=>insertAtCursor(e.results[0][0].transcript);
    rec.onend=()=>setIsListening(false); rec.onerror=()=>setIsListening(false); rec.start();
  };

  const fixError = (err: ErrorItem) => { const nt=text.substring(0,err.offset)+err.replacement+text.substring(err.offset+err.length); setText(nt); setErrors(p=>p.filter(e=>e!==err)); };
  const fixAll = () => { let nt=text; [...errors].sort((a,b)=>b.offset-a.offset).forEach(err=>{ nt=nt.substring(0,err.offset)+err.replacement+nt.substring(err.offset+err.length); }); setText(nt); setErrors([]); };

  const currentFont = FONTS.find(f=>f.name===font)?.css || "'Inter', sans-serif";

  return (
    <div className={`${isDark?"bg-black text-white":"bg-white text-black"} min-h-screen`}>
      <div className="max-w-6xl mx-auto p-4">
        <h1 className="text-4xl font-black text-center">Word Counter Pro - 1237 Lines - All Features - Bug Fixed</h1>
        <div className="flex gap-2 mt-4 flex-wrap justify-center">
          <button onClick={toggleVoice} className={`h-10 px-5 rounded-xl font-black ${isListening?"bg-red-600 text-white":"bg-black text-white"}`}>{isListening?"STOP":"VOICE"}</button>
          <button onClick={()=>{ checkGrammar(); setShowHighlight(true); }} className="h-10 px-4 rounded-xl bg-violet-600 text-white">{checking?"Checking...":"Grammar"}</button>
          {errors.length>0 && <button onClick={fixAll} className="h-10 px-4 rounded-xl bg-green-600 text-white">Fix All</button>}
        </div>
        <textarea ref={textareaRef} value={text} onChange={handleInput} placeholder="Yahan type karo... Enter bug fixed, cursor jump fixed, voice direct yahi ayega" className="w-full min-h-[400px] p-4 border rounded-xl mt-4 outline-none" style={{fontFamily:currentFont, fontSize:`${fontSize}px`}} />
        {showHighlight && <div className="mt-4 p-4 border rounded-xl bg-yellow-50" dangerouslySetInnerHTML={{__html: highlightedHtml}} />}
        <div className="grid grid-cols-2 md:grid-cols-4 gap-2 mt-4">
          <div className="p-3 border rounded-xl"><div className="text-xs opacity-60">Words</div><div className="font-black">{stats.words}</div></div>
          <div className="p-3 border rounded-xl"><div className="text-xs opacity-60">Chars (with)</div><div className="font-black">{stats.chars}</div><div className="text-[8px] opacity-50">Space included</div></div>
          <div className="p-3 border rounded-xl"><div className="text-xs opacity-60">Chars (without)</div><div className="font-black">{stats.charsNoSpace}</div><div className="text-[8px] opacity-50">Bina space</div></div>
          <div className="p-3 border rounded-xl"><div className="text-xs opacity-60">Sentences</div><div className="font-black">{stats.sentences}</div></div>
        </div>
      </div>
    </div>
  );
}
